### ISSUE TITLE
How to use in livebook?

### ISSUE THREAD

**Issue by flupke** [acalejos/merquery#15]
I added Merquery in a new livebook:
```elixir
Mix.install([:merquery])
```
But I get an error when trying to add a Merquery smart cell:
```
19:58:24.433 [error] failed to start smart cell - an exception was raised:
    ** (FunctionClauseError) no function clause matching in Merquery.SmartCell.missing_dep/1
        (merquery 0.1.0) lib/merquery/smart_cell.ex:85: Merquery.SmartCell.missing_dep(nil)
        (merquery 0.1.0) lib/merquery/smart_cell.ex:29: Merquery.SmartCell.init/2
        (kino 0.14.2) lib/kino/js/live/server.ex:91: Kino.JS.Live.Server.call_init/3
        (kino 0.14.2) lib/kino/smart_cell/server.ex:73: Kino.SmartCell.Server.init/1
        (stdlib 6.0.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
```

**Comment by flupke** [comment]
Solved by using the main branch:
```elixir
Mix.install([{:merquery, github: "acalejos/merquery"}])
```
